import { Pelicula } from "./peliculas_info";
import { Genero } from "./peliculas_info";
import { Actores } from "./peliculas_info";

export const PELICULAS : Pelicula[] = [
    {id:1, titulo:"The Dark Knight", anio: 2008,sinopsis: "Batman aumenta las apuestas en su guerra contra el crimen. Con la ayuda de la teniente. Jim Gordon y el Fiscal de Distrito Harvey Dent, Batman se propone desmantelar las organizaciones criminales restantes que plagan las calles. La asociación demuestra ser efectiva, pero pronto se encuentran presa de un reinado de caos desatado por un creciente cerebro criminal conocido por los aterrorizados ciudadanos de Gotham como el Joker.", director:"Chritopher Nolan",portada:"assets/img/Portadas/the dark knight.jpg"},
    {id:2, titulo:"Soul", anio:2020, sinopsis:"Joe Gardner es un profesor de secundaria con un amor por la música jazz. Después de una exitosa audición en el Half Note Club, de repente se mete en un accidente que separa su alma de su cuerpo y es transportado al Seminario You, un centro en el que las almas se desarrollan y ganan pasiones antes de ser transportadas a un niño recién nacido. Joe debe obtener ayuda de las otras almas en entrenamiento, como 22, un alma que ha pasado eones en el Seminario de Ustedes, para regresar a la Tierra.", director:"Pete Docter", portada:"assets/img/Portadas/soul.jpeg"},
    {id:3, titulo:"Parasite", anio:2019, sinopsis:"Todos los desempleados, la familia Ki-taekka tiene un interés peculiar en los parques ricos y glamorosos para su sustento hasta que se enredan en un incidente inesperado.", director:"Joon-ho Bong", portada:"assets/img/Portadas/parasite.jpg"},
    {id:4, titulo:"Hereditary", anio:2018, sinopsis:"Cuando Ellen, la matriarca de la familia Graham, fallece, la familia de su hija comienza a desentrañar secretos crípticos y cada vez más aterradores sobre su ascendencia.", director:"Ari Aster", portada:"assets/img/Portadas/hereditary.jpg"},
    {id:5, titulo:"The Lighthouse", anio:2019, sinopsis:"Dos fareros intentan mantener la cordura mientras viven en una remota y misteriosa isla de Nueva Inglaterra en la década de 1890.", director:"Robert Eggers", portada:"assets/img/Portadas/the lighthouse.jpg"},
    {id:6, titulo:"Gone Girl", anio:2014, sinopsis:"Con la desaparición de su esposa convirtiéndose en el foco de un intenso circo mediático, un hombre ve el foco puesto en él cuando se sospecha que puede no ser inocente.", director:"David Fincher", portada:"assets/img/Portadas/gone girl.jpg"},
    {id:7, titulo:"The Pursuit Happyness", anio:2006, sinopsis:"Un vendedor en apuros toma la custodia de su hijo mientras está a punto de comenzar una carrera profesional que le cambiará la vida.", director:"Gabriel Muccino", portada:"assets/img/Portadas/the pursuit happyness.jpg"},
    {id:8, titulo:"Spider-Man", anio:2002, sinopsis:"Después de ser mordido por una araña genéticamente alterada, el nerd estudiante de secundaria Peter Parker recibe poderes asombrosos para convertirse en el asombroso superhéroe conocido como Spider-Man.", director:"Sam Raimi", portada:"assets/img/Portadas/spider man.jpg"},
    {id:9, titulo:"The Pianist", anio:2002, sinopsis:"La verdadera historia del pianista Wadadysinaw Szpilman muestra las experiencias en Varsovia durante la ocupación nazi. Cuando los judíos de la ciudad se ven obligados a entrar en un gueto, Szpilman encuentra trabajo jugando en un café; y cuando su familia es deportada en 1942, se queda atrás, trabaja por un tiempo como trabajador, y finalmente se esconde en las ruinas de la ciudad devastada por la guerra.", director:"Roman Polanski", portada:"assets/img/Portadas/the pianist.jpg"},
    {id:10, titulo:"Whiplash", anio:2014, sinopsis:"Bajo la dirección de un despiadado instructor, un joven y talentoso baterista comienza a buscar la perfección a cualquier precio, incluso su humanidad.", director:"Damien Chazelle", portada:"assets/img/Portadas/whiplash.jpg"},
    {id:11, titulo:"Eternal Sunshine of The Spotless Mind", anio:2004, sinopsis:"Joel Barish, desconsolado porque su novia se sometió a un procedimiento para borrarlo de su memoria, decide hacer lo mismo. Sin embargo, mientras observa cómo sus recuerdos de ella se desvanecen, se da cuenta de que todavía la ama y puede ser demasiado tarde para corregir su error.", director:"Michel Gondry", portada:"assets/img/Portadas/eternal sunshine.jpg"},
    {id:12, titulo:"Cast Away", anio:2000, sinopsis:"Chuck, un alto directivo internacional de FedEx, y Kelly, Ph.D. estudiante, están enamorados y encaminados hacia el matrimonio. Luego, el avión de Chuck a Malasia se estrella en el mar durante una terrible tormenta. Es el único superviviente y llega a una pequeña isla sin nada más que algunos restos de la carga del avión.", director:"Robert Zemeckis", portada:"assets/img/Portadas/cast away.jpg"},
    {id:13, titulo:"The Truman Show", anio:1998, sinopsis:"Truman Burbank es la estrella de The Truman Show, un reality show de 24 horas al día que transmite todos los aspectos de su vida sin su conocimiento. Toda su vida ha sido una telenovela interminable para el consumo del resto del mundo. Y todo el mundo que conoce, incluyendo a su esposa y su mejor amigo es realmente un actor, pagado para ser parte de su vida.", director:"Peter Weir", portada:"assets/img/Portadas/the truman show.jpg"},
    {id:14, titulo:"The Shawnshank Redemption", anio:1994, sinopsis:"Enmarcado en la década de 1940 por el doble asesinato de su esposa y su amante, el destacado banquero Andy Dufresne comienza una nueva vida en la prisión de Shawshank, donde pone sus habilidades contables a trabajar para un alcaide amoral. Durante su largo período en prisión, Dufresne llega a ser admirado por los otros reclusos –, incluido un prisionero mayor llamado Red – por su integridad y su insaciable sentido de esperanza.", director:"Frank Darabont", portada:"assets/img/Portadas/shawnshank.jpg"},
    {id:15, titulo:"Rocky", anio:1976, sinopsis:"Cuando el campeón mundial de boxeo de peso pesado, Apollo Creed quiere darle a un luchador desconocido una oportunidad por el título como un truco publicitario, sus manejadores eligen la palooka Rocky Balboa, un coleccionista sin educación para un prestamista de Filadelfia. Rocky se une al entrenador Mickey Goldmill para aprovechar al máximo este descanso único en la vida.", director:"John G. Avildsen", portada:"assets/img/Portadas/rocky.jpg"},
    {id:16, titulo:"Back to the Future", anio:1985, sinopsis:"El adolescente de los ochenta Marty McFly es enviado accidentalmente al pasado, a 1955, interrumpiendo sin querer el primer encuentro de sus padres y atrayendo el interés romántico de su madre. Marty debe reparar el daño a la historia reavivando el romance de sus padres y, con la ayuda de su excéntrico amigo inventor Doc Brown, regresar a 1985.", director:"Robert Zemeckis", portada:"assets/img/Portadas/back to the future.jpg"},
    {id:17, titulo:"Everything Everywhere All at Once", anio:2022, sinopsis:"Una anciana inmigrante china se ve envuelta en una loca aventura, donde ella sola puede salvar lo que es importante para ella al conectarse con las vidas que podría haber llevado en otros universos.", director:"Daniel Scheinert, Daniel Kwan", portada:"assets/img/Portadas/everything everywhere all at once.jpg"},
    {id:18, titulo: "127 Hours", anio:2010, sinopsis:"La historia real de la extraordinaria aventura del alpinista Aron Ralston para salvarse después de que una roca caída choca contra su brazo y lo atrapa en un cañón aislado en Utah.", director:"Danny Boyle", portada:"assets/img/Portadas/127 hours.jpg"}
]

export const GENEROS : Genero [] = [
    {id:1, genero: "Acción"},
    {id:2, genero: "Aventura"},
    {id:3, genero: "Catástrofe"},
    {id:4, genero: "Ciencia Ficción"},
    {id:5, genero: "Comedia"},
    {id:6, genero: "Documentales"},
    {id:7, genero: "Drama"},
    {id:8, genero: "Fantasía"},
    {id:9, genero: "Musicales"},
    {id:10, genero: "Superhéroes"},
    {id:11, genero: "Suspenso"},
    {id:12, genero: "Terror"},
    {id:13, genero: "Thriller"},
]

export const ACTORES : Actores [] = [
    {id:1, actor:"Christian Bale", foto:"assets/img/Actores/Christian Bale.jpg"},
    {id:2, actor:"Heath Ledger", foto:"assets/img/Actores/Heath Ledger.jpg"},
    {id:3, actor:"Gary Oldman", foto:"assets/img/Actores/Gary Oldman.jpg"},
    {id:4, actor:"Aaron Eckhart", foto:"assets/img/Actores/Aaron Eckhart.jpg"},
    {id:5, actor:"Jamie Foxx", foto:"assets/img/Actores/Jamie Foxx.jpg"},
    {id:6, actor:"Tina Fey", foto:"assets/img/Actores/Tina Fey.jpg"},
    {id:7, actor:"Toni Collette", foto:"assets/img/Actores/Toni Collette.jpg"},
    {id:8, actor:"Alex Wolff", foto:"assets/img/Actores/Alex Wolff.jpg"},
    {id:9, actor:"Gabriel Byrne", foto:"assets/img/Actores/Gabriel Byrne.jpg"},
    {id:10, actor:"Robert Pattinson", foto:"assets/img/Actores/Robert Pattinson.jpg"},
    {id:11, actor:"Willem Dafoe", foto:"assets/img/Actores/Willem Dafoe.jpg"},
    {id:12, actor:"Ben Affleck", foto:"assets/img/Actores/Ben Affleck.jpg"},
    {id:13, actor:"Pike Rosamund", foto:"assets/img/Actores/Pike Rosamund.jpg"},
    {id:14, actor:"Tobey Maguire", foto:"assets/img/Actores/Tobey Maguire.jpg"},
    {id:15, actor:"Kirsten Dunst", foto:"assets/img/Actores/Kirsten Dunst.jpg"},
    {id:16, actor:"J.K. Simmons", foto:"assets/img/Actores/J.K. Simmons.jpg"},
    {id:17, actor:"Milles Teller", foto:"assets/img/Actores/Milles Teller.jpg"},
    {id:18, actor:"James Franco", foto:"assets/img/Actores/James Franco.jpg"},
    {id:19, actor:"Adriend Brody", foto:"assets/img/Actores/Adriend Brody.jpg"},
    {id:20, actor:"Jim Carrey", foto:"assets/img/Actores/Jim Carrey.jpg"},
    {id:21, actor:"Kate Winslet", foto:"assets/img/Actores/Kate Winslet.jpg"},
    {id:22, actor:"Tom Hanks", foto:"assets/img/Actores/Tom Hanks.jpg"},
    {id:23, actor:"Tim Robbins", foto:"assets/img/Actores/Tim Robbins.jpg"},
    {id:24, actor:"Morgan Freeman", foto:"assets/img/Actores/Morgan Freeman.jpg"},
    {id:25, actor:"Silvester Stallone", foto:"assets/img/Actores/Silvester Stallone.jpg"},
    {id:26, actor:"Carl Weathers", foto:"assets/img/Actores/Carl Weathers.jpg"},
    {id:27, actor:"Michael J. Fox", foto:"assets/img/Actores/Michael J. Fox.jpg"},
    {id:28, actor:"Chistopher Lloyd", foto:"assets/img/Actores/Chistopher Lloyd.jpg"},
    {id:29, actor:"Michelle Yeoh", foto:"assets/img/Actores/Michelle Yeoh.jpg"},
    {id:30, actor:"He Huy Quan", foto:"assets/img/Actores/He Huy Quan.jpg"},
    {id:31, actor:"Jamie Lee Curtis", foto:"assets/img/Actores/Jamie Lee Curtis.jpg"},
]